export enum ADMIN_USER {
  'NORMAL' = 'NORMAL',
  'SUPER' = 'SUPER',
}
export const CONST_ADMIN_USER = Object.values(ADMIN_USER);

export enum CHANGUP_CONTRACT {
  'C_END' = 'C_END',
  'C_PROCEEDING' = 'C_PROCEEDING',
}
export const CONST_CHANGUP_CONTRACT = Object.values(CHANGUP_CONTRACT);

export enum FOUNDER_CONSULT {
  'F_ADD_TOUR' = 'F_ADD_TOUR',
  'F_CANNOT_CONTACT' = 'F_CANNOT_CONTACT',
  'F_CONTACT_CANCEL' = 'F_CONTACT_CANCEL',
  'F_CONTACT_FIN' = 'F_CONTACT_FIN',
  'F_CONTACT_READY' = 'F_CONTACT_READY',
  'F_DROP' = 'F_DROP',
  'F_FIN_CONTRACT' = 'F_FIN_CONTRACT',
  'F_MEETING_FIN' = 'F_MEETING_FIN',
  'F_NEW_REG' = 'F_NEW_REG',
  'F_PROCEEDING' = 'F_PROCEEDING',
  'F_PROCEEDING_TOUR' = 'F_PROCEEDING_TOUR',
  'F_RECONTACT_REQUEST' = 'F_RECONTACT_REQUEST',
  'F_WATING_CONTRACT' = 'F_WATING_CONTRACT',
}
export const CONST_FOUNDER_CONSULT = Object.values(FOUNDER_CONSULT);

export enum PRODUCT_CONSULT {
  'P_ADD_TOUR' = 'P_ADD_TOUR',
  'P_CANNOT_CONTACT' = 'P_CANNOT_CONTACT',
  'P_CONTACT_CANCEL' = 'P_CONTACT_CANCEL',
  'P_CONTACT_FIN' = 'P_CONTACT_FIN',
  'P_CONTACT_READY' = 'P_CONTACT_READY',
  'P_DROP' = 'P_DROP',
  'P_MEETING_FIN' = 'P_MEETING_FIN',
  'P_NEW_REG' = 'P_NEW_REG',
  'P_PROCEEDING' = 'P_PROCEEDING',
  'P_PROCEEDING_TOUR' = 'P_PROCEEDING_TOUR',
  'P_RECONTACT_REQUEST' = 'P_RECONTACT_REQUEST',
  'P_WATING_CONTRACT' = 'P_WATING_CONTRACT',
}
export const CONST_PRODUCT_CONSULT = Object.values(PRODUCT_CONSULT);

export enum SPACE {
  'ALL' = 'ALL',
  'ANALYSIS_FIN' = 'ANALYSIS_FIN',
  'ANALYSIS_PROGRESS' = 'ANALYSIS_PROGRESS',
  'ANALYSIS_READY' = 'ANALYSIS_READY',
  'BRAND' = 'BRAND',
  'DAILY' = 'DAILY',
  'HH' = 'HH',
  'HL' = 'HL',
  'HM' = 'HM',
  'KITCHEN' = 'KITCHEN',
  'LH' = 'LH',
  'LL' = 'LL',
  'LM' = 'LM',
  'MATCH' = 'MATCH',
  'MH' = 'MH',
  'ML' = 'ML',
  'MM' = 'MM',
  'SPACE_CONDUCT_EXP' = 'SPACE_CONDUCT_EXP',
  'SPACE_DROP' = 'SPACE_DROP',
  'SPACE_FIN_CONTRACT' = 'SPACE_FIN_CONTRACT',
  'SPACE_FOR_ANALYSIS' = 'SPACE_FOR_ANALYSIS',
  'SPACE_IN_CONSUL' = 'SPACE_IN_CONSUL',
  'SPACE_NEW_REG' = 'SPACE_NEW_REG',
  'SPACE_RE_PHOTO' = 'SPACE_RE_PHOTO',
  'SPACE_REG_COM' = 'SPACE_REG_COM',
  'SPACE_WATING_TOUR' = 'SPACE_WATING_TOUR',
  'TIME' = 'TIME',
  'UNBRAND' = 'UNBRAND',
  'WEEKDAY' = 'WEEKDAY',
  'WEEKEND' = 'WEEKEND',
}
export const CONST_SPACE = Object.values(SPACE);

export enum SPACE_CONTRACT {
  'S_END' = 'S_END',
  'S_PROCEEDING' = 'S_PROCEEDING',
}
export const CONST_SPACE_CONTRACT = Object.values(SPACE_CONTRACT);
